version: '3.12'

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: "app/Dockerfile"
    container_name: "flaskter"
    env_file:
      - ".env.docker"
    restart: "always"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: "postgres"
    image: postgres:latest
    env_file:
      - ".env.docker"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
